### PR TITLE
Add build ci stage

### PR DESCRIPTION
**Pull request by abarichello**
- [x] Add static files: default server configs, placeholder player data, legal.txt, etc. Ideally group everything on main repo
- [x] Add minhook dll
- [x] Trigger on release
- [x] Add version env to gh actions secrets panel

### CODE REVIEW

**Comment by abarichello** [comment]
Here's an [example pipeline](https://github.com/abarichello/Northstar/actions/runs/1689826454) and an [example output](https://github.com/abarichello/Northstar/suites/4916536718/artifacts/141695393).

**Comment by abarichello** [comment]
To use this pipeline properly you have to:
- Update `NORTHSTAR_VERSION` in secrets panel. https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository
- Create a release in `northstarlauncher`, `northstarmods` and `northstar` repos (in this order). The release tag should match the same one used in the secrets panel.
- Wait around 3 minutes for it to build 
- Upload the generated artifact to the release page in northstar main repo

**Comment by GeckoEidechse** [comment]
> * Update `NORTHSTAR_VERSION` in secrets panel.

Couldn't we just use the name of the release tag for `NORTHSTAR_VERSION`? That way one doesn't even have to sync secret and release tag.

**Comment by abarichello** [comment]
> Couldn't we just use the name of the release tag for `NORTHSTAR_VERSION`? That way one doesn't even have to sync secret and release tag.

I think `GITHUB_REF` should do that, i'll update it later.
https://docs.github.com/en/actions/learn-github-actions/environment-variables

**Comment by abarichello** [comment]
This is ready for merge, we should probably create a dummy pre-release in the main repo to trigger the CI and check that everything is 100% correct before using this for future releases.

**Comment by GeckoEidechse** [comment]
> [...] we should probably create a dummy pre-release in the main repo to trigger the CI and check that everything is 100% correct before using this for future releases.

Probably best to test that on an internal fork, before someone starts downloading potentially borked pre-releases.

**Comment by abarichello** [comment]
Also works

**Comment by abarichello** [comment]
Linking with https://github.com/R2Northstar/NorthstarLauncher/issues/47

**Pull request merged**
