### PR TITLE
Add NorthstarNavs link to README

### PR DESCRIPTION
**Pull request by F1F7Y**
Hi Gecko :)

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Question is, do we at this point then also wanna add Stubs, Docs, and Wiki? ^^

**Comment by F1F7Y** [comment]
All three of those are already there ?

**Comment by GeckoEidechse** [comment]
I'm blind lol

**Comment by GeckoEidechse** [comment]
Yeah, then it's fine by me ^^

**Pull request merged**
