### PR TITLE
Add badge for downloads of current version

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Rendered:

image

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Could also do total downloads but those will spike with every new release so its gonna start feeling like those stats are boosted the more releases we make.

> GitHub release downloads (Total)

**Comment by Seyithantas** [comment]
> İşlendi:
> 
> resim

**Comment by ASpoonPlaysGames** [comment]
if possible, can you do downloads on x.y instead of just the latest release which would be x.y.z as a lot of people dont download the little patches and stuff and this would probably better represent it?

**Comment by GeckoEidechse** [comment]
> if possible, can you do downloads on x.y instead of just the latest release which would be x.y.z as a lot of people dont download the little patches and stuff and this would probably better represent it?

I don't think [shields.io](https://shields.io/) supports that sadly :/

**Pull request merged**
