### PR TITLE
Created INSTALL.md for MAIN REPO and Edited README.md

### PR DESCRIPTION
**Pull request by FutzMonitor**
I decided to create an INSTALL.md file for the main repo providing a more detailed set of instructions on how to download the client. I visited the Discord and realized that the instructions on the repo were not very clear, so I decided to write something for the community.

### CODE REVIEW

**Comment by georgewoodall82** [comment]
Good work but wouldn't this be better added onto the wiki?

**Comment by FutzMonitor** [comment]
> 

I don't really have experience working on Wiki pages. I thought about just adding a INSTALL.md that can be linked to in the read me file.

**Comment by FutzMonitor** [comment]
I edited the README file in my fork to mention the instructions in INSTALL.md.

**Comment by LaercioMBR** [comment]
One suggestion:

Github's .md doesn't allow for Embedded video links currently, but the next best thing is tricking the user in clicking a gif of the video and it opening the real video with sound.

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#youtube-videos

https://stackoverflow.com/questions/11804820/how-can-i-embed-a-youtube-video-on-github-wiki-pages

https://stackoverflow.com/questions/4279611/how-to-embed-a-video-into-github-readme-md?rq=1

**Comment by georgewoodall82** [comment]
> One suggestion:
> 
> Github's .md doesn't allow for Embedded video links currently, but the next best thing is tricking the user in clicking a gif of the video and it opening the real video with sound.
> 
> https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#youtube-videos
> 
> https://stackoverflow.com/questions/11804820/how-can-i-embed-a-youtube-video-on-github-wiki-pages
> 
> https://stackoverflow.com/questions/4279611/how-to-embed-a-video-into-github-readme-md?rq=1

how is there videos at the bottom of this page? https://github.com/alelievr/Mixture/blob/0.4.0/README.md

**Comment by LaercioMBR** [comment]
> > One suggestion:
> > Github's .md doesn't allow for Embedded video links currently, but the next best thing is tricking the user in clicking a gif of the video and it opening the real video with sound.
> > https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#youtube-videos
> > https://stackoverflow.com/questions/11804820/how-can-i-embed-a-youtube-video-on-github-wiki-pages
> > https://stackoverflow.com/questions/4279611/how-to-embed-a-video-into-github-readme-md?rq=1
> 
> how is there videos at the bottom of this page? https://github.com/alelievr/Mixture/blob/0.4.0/README.md

If I read correctly, it was because they directly uploaded the specific video themselves to the .md file, instead of referencing any random video on the internet with just a link.

Those links are a way to MacGyver it with any random video you want.

**Comment by JJRcop** [comment]
Regardless of what's actually in this (provided it's sensible), the README.md file **MUST** have some instructions to get started, because otherwise new people coming to this page get lost in the developer-oriented language and tips.

They don't know what the GitHub wiki is, you have to show them, at the very least.

**Comment by FutzMonitor** [comment]
> One suggestion:
> 
> Github's .md doesn't allow for Embedded video links currently, but the next best thing is tricking the user in clicking a gif of the video and it opening the real video with sound.
> 
> Having a big gif/video thing is a lot more welcoming and direct for newer folk than just small blue link in a random word. Not too noticeable from the background if you use dark mode too.
> 
> https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#youtube-videos
> 
> https://stackoverflow.com/questions/11804820/how-can-i-embed-a-youtube-video-on-github-wiki-pages
> 
> https://stackoverflow.com/questions/4279611/how-to-embed-a-video-into-github-readme-md?rq=1

Per your recommendation, I removed the obscure *here* hyperlink and replaced it with an image link using the provided resources. Thank you so much for your feedback!

**Comment by FutzMonitor** [comment]
> Having

I agree. I don't know how to Wiki pages work on GitHub but I don't want to mess with the setup or create new pages. Instead, I decided to just direct newcomers to the INSTALL.md which I believe is pretty detailed.

**Comment by abarichello** [comment]
Adding a compilation guide (specially for the launcher) would also be useful.

**Comment by VITALISED** [comment]
Might not be relevant but if there were some contribution and issue guidelines that'd be good

**Comment by InHooman** [comment]
Also needs instructions for Origin and EA App

**Review by abarichello — CHANGES_REQUESTED** [review]
Now that we have an official wiki page you can remove this file and add important links to the README such as: https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/basic-setup

**Pull request closed without merging**
